FROM ubuntu:16.04
RUN apt-get update && apt-get install  tree  # -f for silent mode
RUN touch /tmp/2.txt
RUN touch /tmp/3.txt
RUN touch /tmp/4.txt
RUN touch /tmp/5.txt
RUN touch /tmp/6.txt
RUN touch /tmp/7.txt